# fly.toml app configuration file generated for my-year-compass-server on 2024-03-07T17:18:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-year-compass-server'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
